kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-app
  namespace: nfs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:
        - name: httpd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /data
